// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function IsUp():Promise<boolean>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
