// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsUp() {
  return window['go']['server']['ServerHandler']['IsUp']();
}

export function OnStartup(arg1) {
  return window['go']['server']['ServerHandler']['OnStartup'](arg1);
}

export function SetPort(arg1) {
  return window['go']['server']['ServerHandler']['SetPort'](arg1);
}

export function StartServer() {
  return window['go']['server']['ServerHandler']['StartServer']();
}

export function StopServer() {
  return window['go']['server']['ServerHandler']['StopServer']();
}
